export const CITIES = [
  { code: 'AE-DU', name: 'Dubai', country: 'United Arab Emirates' },
  { code: 'AE-AZ', name: 'Abu Dhabi', country: 'United Arab Emirates' },
  { code: 'AE-SH', name: 'Sharjah', country: 'United Arab Emirates' },
  { code: 'AE-AJ', name: 'Ajman', country: 'United Arab Emirates' },
  { code: 'AE-UQ', name: 'Umm Al Quwain', country: 'United Arab Emirates' },
  { code: 'AE-FU', name: 'Fujairah', country: 'United Arab Emirates' },
  { code: 'AE-RK', name: 'Ras Al Khaimah', country: 'United Arab Emirates' },
  { code: 'SA-RI', name: 'Riyadh', country: 'Saudi Arabia' },
  { code: 'SA-JE', name: 'Jeddah', country: 'Saudi Arabia' },
  { code: 'SA-ME', name: 'Mecca', country: 'Saudi Arabia' },
  { code: 'SA-MD', name: 'Medina', country: 'Saudi Arabia' },
  { code: 'SA-DA', name: 'Dammam', country: 'Saudi Arabia' },
  { code: 'SA-KH', name: 'Khobar', country: 'Saudi Arabia' },
  { code: 'KW-KW', name: 'Kuwait City', country: 'Kuwait' },
  { code: 'BH-MA', name: 'Manama', country: 'Bahrain' },
  { code: 'QA-DO', name: 'Doha', country: 'Qatar' },
  { code: 'OM-MU', name: 'Muscat', country: 'Oman' },
  { code: 'OM-SA', name: 'Salalah', country: 'Oman' },
  { code: 'EG-CA', name: 'Cairo', country: 'Egypt' },
  { code: 'EG-AL', name: 'Alexandria', country: 'Egypt' },
  { code: 'JO-AM', name: 'Amman', country: 'Jordan' },
  { code: 'LB-BE', name: 'Beirut', country: 'Lebanon' },
  { code: 'MA-CA', name: 'Casablanca', country: 'Morocco' },
  { code: 'MA-RA', name: 'Rabat', country: 'Morocco' },
  { code: 'MA-MA', name: 'Marrakech', country: 'Morocco' },
  { code: 'TN-TU', name: 'Tunis', country: 'Tunisia' },
  { code: 'DZ-AL', name: 'Algiers', country: 'Algeria' },
  { code: 'US-NY', name: 'New York', country: 'United States' },
  { code: 'US-LA', name: 'Los Angeles', country: 'United States' },
  { code: 'US-CH', name: 'Chicago', country: 'United States' },
  { code: 'US-MI', name: 'Miami', country: 'United States' },
  { code: 'GB-LO', name: 'London', country: 'United Kingdom' },
  { code: 'FR-PA', name: 'Paris', country: 'France' },
  { code: 'IT-MI', name: 'Milan', country: 'Italy' },
  { code: 'IT-RO', name: 'Rome', country: 'Italy' },
  { code: 'DE-BE', name: 'Berlin', country: 'Germany' },
  { code: 'ES-MA', name: 'Madrid', country: 'Spain' },
  { code: 'ES-BA', name: 'Barcelona', country: 'Spain' },
  { code: 'TR-IS', name: 'Istanbul', country: 'Turkey' },
  { code: 'TR-AN', name: 'Ankara', country: 'Turkey' },
  { code: 'SG-SG', name: 'Singapore', country: 'Singapore' },
  { code: 'MY-KL', name: 'Kuala Lumpur', country: 'Malaysia' },
  { code: 'TH-BK', name: 'Bangkok', country: 'Thailand' },
  { code: 'ID-JA', name: 'Jakarta', country: 'Indonesia' },
  { code: 'PH-MA', name: 'Manila', country: 'Philippines' },
  { code: 'IN-MU', name: 'Mumbai', country: 'India' },
  { code: 'IN-DE', name: 'Delhi', country: 'India' },
  { code: 'IN-BA', name: 'Bangalore', country: 'India' },
  { code: 'PK-KA', name: 'Karachi', country: 'Pakistan' },
  { code: 'PK-LA', name: 'Lahore', country: 'Pakistan' },
  { code: 'BD-DH', name: 'Dhaka', country: 'Bangladesh' },
  { code: 'CN-BE', name: 'Beijing', country: 'China' },
  { code: 'CN-SH', name: 'Shanghai', country: 'China' },
  { code: 'JP-TO', name: 'Tokyo', country: 'Japan' },
  { code: 'KR-SE', name: 'Seoul', country: 'South Korea' },
  { code: 'AU-SY', name: 'Sydney', country: 'Australia' },
  { code: 'AU-ME', name: 'Melbourne', country: 'Australia' },
  { code: 'CA-TO', name: 'Toronto', country: 'Canada' },
  { code: 'CA-VA', name: 'Vancouver', country: 'Canada' },
  { code: 'BR-SP', name: 'São Paulo', country: 'Brazil' },
  { code: 'BR-RJ', name: 'Rio de Janeiro', country: 'Brazil' },
  { code: 'AR-BA', name: 'Buenos Aires', country: 'Argentina' },
  { code: 'MX-MC', name: 'Mexico City', country: 'Mexico' },
  { code: 'ZA-JO', name: 'Johannesburg', country: 'South Africa' },
  { code: 'ZA-CT', name: 'Cape Town', country: 'South Africa' },
  { code: 'NG-LA', name: 'Lagos', country: 'Nigeria' },
  { code: 'KE-NA', name: 'Nairobi', country: 'Kenya' },
  { code: 'RU-MO', name: 'Moscow', country: 'Russia' },
  { code: 'RU-SP', name: 'Saint Petersburg', country: 'Russia' }
];