export const CITIES = [
  // United Arab Emirates
  { code: 'AE-DU', name: 'Dubai', country: 'United Arab Emirates' },
  { code: 'AE-AZ', name: 'Abu Dhabi', country: 'United Arab Emirates' },
  { code: 'AE-SH', name: 'Sharjah', country: 'United Arab Emirates' },
  { code: 'AE-AJ', name: 'Ajman', country: 'United Arab Emirates' },
  { code: 'AE-UQ', name: 'Umm Al Quwain', country: 'United Arab Emirates' },
  { code: 'AE-FU', name: 'Fujairah', country: 'United Arab Emirates' },
  { code: 'AE-RK', name: 'Ras Al Khaimah', country: 'United Arab Emirates' },
  { code: 'AE-AA', name: 'Al Ain', country: 'United Arab Emirates' },
  
  // Saudi Arabia
  { code: 'SA-RI', name: 'Riyadh', country: 'Saudi Arabia' },
  { code: 'SA-JE', name: 'Jeddah', country: 'Saudi Arabia' },
  { code: 'SA-ME', name: 'Mecca', country: 'Saudi Arabia' },
  { code: 'SA-MD', name: 'Medina', country: 'Saudi Arabia' },
  { code: 'SA-DA', name: 'Dammam', country: 'Saudi Arabia' },
  { code: 'SA-KH', name: 'Khobar', country: 'Saudi Arabia' },
  { code: 'SA-TA', name: 'Taif', country: 'Saudi Arabia' },
  { code: 'SA-TB', name: 'Tabuk', country: 'Saudi Arabia' },
  { code: 'SA-KI', name: 'Khamis Mushait', country: 'Saudi Arabia' },
  { code: 'SA-BU', name: 'Buraidah', country: 'Saudi Arabia' },
  { code: 'SA-HA', name: 'Hail', country: 'Saudi Arabia' },
  { code: 'SA-HO', name: 'Hofuf', country: 'Saudi Arabia' },
  { code: 'SA-JU', name: 'Jubail', country: 'Saudi Arabia' },
  { code: 'SA-YA', name: 'Yanbu', country: 'Saudi Arabia' },
  
  // Kuwait
  { code: 'KW-KW', name: 'Kuwait City', country: 'Kuwait' },
  { code: 'KW-AL', name: 'Al Ahmadi', country: 'Kuwait' },
  { code: 'KW-HA', name: 'Hawalli', country: 'Kuwait' },
  { code: 'KW-SA', name: 'Salmiya', country: 'Kuwait' },
  
  // Qatar
  { code: 'QA-DO', name: 'Doha', country: 'Qatar' },
  { code: 'QA-AL', name: 'Al Wakrah', country: 'Qatar' },
  { code: 'QA-AR', name: 'Al Rayyan', country: 'Qatar' },
  { code: 'QA-DU', name: 'Dukhan', country: 'Qatar' },
  
  // Bahrain
  { code: 'BH-MA', name: 'Manama', country: 'Bahrain' },
  { code: 'BH-MU', name: 'Muharraq', country: 'Bahrain' },
  { code: 'BH-RI', name: 'Riffa', country: 'Bahrain' },
  { code: 'BH-IS', name: 'Isa Town', country: 'Bahrain' },
  
  // Oman
  { code: 'OM-MU', name: 'Muscat', country: 'Oman' },
  { code: 'OM-SA', name: 'Salalah', country: 'Oman' },
  { code: 'OM-SO', name: 'Sohar', country: 'Oman' },
  { code: 'OM-NI', name: 'Nizwa', country: 'Oman' },
  
  // Egypt
  { code: 'EG-CA', name: 'Cairo', country: 'Egypt' },
  { code: 'EG-AL', name: 'Alexandria', country: 'Egypt' },
  { code: 'EG-GI', name: 'Giza', country: 'Egypt' },
  { code: 'EG-LU', name: 'Luxor', country: 'Egypt' },
  { code: 'EG-AS', name: 'Aswan', country: 'Egypt' },
  { code: 'EG-SH', name: 'Sharm El Sheikh', country: 'Egypt' },
  { code: 'EG-HU', name: 'Hurghada', country: 'Egypt' },
  
  // Jordan
  { code: 'JO-AM', name: 'Amman', country: 'Jordan' },
  { code: 'JO-ZA', name: 'Zarqa', country: 'Jordan' },
  { code: 'JO-IR', name: 'Irbid', country: 'Jordan' },
  { code: 'JO-AQ', name: 'Aqaba', country: 'Jordan' },
  { code: 'JO-SA', name: 'Salt', country: 'Jordan' },
  
  // Lebanon
  { code: 'LB-BE', name: 'Beirut', country: 'Lebanon' },
  { code: 'LB-TR', name: 'Tripoli', country: 'Lebanon' },
  { code: 'LB-SI', name: 'Sidon', country: 'Lebanon' },
  { code: 'LB-TY', name: 'Tyre', country: 'Lebanon' },
  { code: 'LB-ZA', name: 'Zahle', country: 'Lebanon' },
  
  // Morocco
  { code: 'MA-CA', name: 'Casablanca', country: 'Morocco' },
  { code: 'MA-RA', name: 'Rabat', country: 'Morocco' },
  { code: 'MA-MA', name: 'Marrakech', country: 'Morocco' },
  { code: 'MA-FE', name: 'Fez', country: 'Morocco' },
  { code: 'MA-TA', name: 'Tangier', country: 'Morocco' },
  { code: 'MA-AG', name: 'Agadir', country: 'Morocco' },
  { code: 'MA-ME', name: 'Meknes', country: 'Morocco' },
  
  // Tunisia
  { code: 'TN-TU', name: 'Tunis', country: 'Tunisia' },
  { code: 'TN-SF', name: 'Sfax', country: 'Tunisia' },
  { code: 'TN-SO', name: 'Sousse', country: 'Tunisia' },
  { code: 'TN-ET', name: 'Ettadhamen', country: 'Tunisia' },
  
  // Algeria
  { code: 'DZ-AL', name: 'Algiers', country: 'Algeria' },
  { code: 'DZ-OR', name: 'Oran', country: 'Algeria' },
  { code: 'DZ-CO', name: 'Constantine', country: 'Algeria' },
  { code: 'DZ-AN', name: 'Annaba', country: 'Algeria' },
  
  // United States
  { code: 'US-NY', name: 'New York', country: 'United States' },
  { code: 'US-LA', name: 'Los Angeles', country: 'United States' },
  { code: 'US-CH', name: 'Chicago', country: 'United States' },
  { code: 'US-HO', name: 'Houston', country: 'United States' },
  { code: 'US-PH', name: 'Philadelphia', country: 'United States' },
  { code: 'US-PX', name: 'Phoenix', country: 'United States' },
  { code: 'US-SA', name: 'San Antonio', country: 'United States' },
  { code: 'US-SD', name: 'San Diego', country: 'United States' },
  { code: 'US-DA', name: 'Dallas', country: 'United States' },
  { code: 'US-SJ', name: 'San Jose', country: 'United States' },
  { code: 'US-AU', name: 'Austin', country: 'United States' },
  { code: 'US-JA', name: 'Jacksonville', country: 'United States' },
  { code: 'US-SF', name: 'San Francisco', country: 'United States' },
  { code: 'US-IN', name: 'Indianapolis', country: 'United States' },
  { code: 'US-CO', name: 'Columbus', country: 'United States' },
  { code: 'US-FW', name: 'Fort Worth', country: 'United States' },
  { code: 'US-CH', name: 'Charlotte', country: 'United States' },
  { code: 'US-SE', name: 'Seattle', country: 'United States' },
  { code: 'US-DE', name: 'Denver', country: 'United States' },
  { code: 'US-WA', name: 'Washington', country: 'United States' },
  { code: 'US-BO', name: 'Boston', country: 'United States' },
  { code: 'US-EL', name: 'El Paso', country: 'United States' },
  { code: 'US-NA', name: 'Nashville', country: 'United States' },
  { code: 'US-BA', name: 'Baltimore', country: 'United States' },
  { code: 'US-OK', name: 'Oklahoma City', country: 'United States' },
  { code: 'US-LO', name: 'Louisville', country: 'United States' },
  { code: 'US-PO', name: 'Portland', country: 'United States' },
  { code: 'US-LA', name: 'Las Vegas', country: 'United States' },
  { code: 'US-MG', name: 'Memphis', country: 'United States' },
  { code: 'US-DT', name: 'Detroit', country: 'United States' },
  { code: 'US-MI', name: 'Miami', country: 'United States' },
  
  // Canada
  { code: 'CA-TO', name: 'Toronto', country: 'Canada' },
  { code: 'CA-MO', name: 'Montreal', country: 'Canada' },
  { code: 'CA-VA', name: 'Vancouver', country: 'Canada' },
  { code: 'CA-CA', name: 'Calgary', country: 'Canada' },
  { code: 'CA-ED', name: 'Edmonton', country: 'Canada' },
  { code: 'CA-OT', name: 'Ottawa', country: 'Canada' },
  { code: 'CA-WI', name: 'Winnipeg', country: 'Canada' },
  { code: 'CA-QU', name: 'Quebec City', country: 'Canada' },
  { code: 'CA-HA', name: 'Hamilton', country: 'Canada' },
  { code: 'CA-KI', name: 'Kitchener', country: 'Canada' },
  
  // United Kingdom
  { code: 'GB-LO', name: 'London', country: 'United Kingdom' },
  { code: 'GB-BI', name: 'Birmingham', country: 'United Kingdom' },
  { code: 'GB-MA', name: 'Manchester', country: 'United Kingdom' },
  { code: 'GB-GL', name: 'Glasgow', country: 'United Kingdom' },
  { code: 'GB-LI', name: 'Liverpool', country: 'United Kingdom' },
  { code: 'GB-ED', name: 'Edinburgh', country: 'United Kingdom' },
  { code: 'GB-LE', name: 'Leeds', country: 'United Kingdom' },
  { code: 'GB-SH', name: 'Sheffield', country: 'United Kingdom' },
  { code: 'GB-BR', name: 'Bristol', country: 'United Kingdom' },
  { code: 'GB-CA', name: 'Cardiff', country: 'United Kingdom' },
  
  // France
  { code: 'FR-PA', name: 'Paris', country: 'France' },
  { code: 'FR-MA', name: 'Marseille', country: 'France' },
  { code: 'FR-LY', name: 'Lyon', country: 'France' },
  { code: 'FR-TO', name: 'Toulouse', country: 'France' },
  { code: 'FR-NI', name: 'Nice', country: 'France' },
  { code: 'FR-NA', name: 'Nantes', country: 'France' },
  { code: 'FR-ST', name: 'Strasbourg', country: 'France' },
  { code: 'FR-MO', name: 'Montpellier', country: 'France' },
  { code: 'FR-BO', name: 'Bordeaux', country: 'France' },
  { code: 'FR-LI', name: 'Lille', country: 'France' },
  
  // Germany
  { code: 'DE-BE', name: 'Berlin', country: 'Germany' },
  { code: 'DE-HA', name: 'Hamburg', country: 'Germany' },
  { code: 'DE-MU', name: 'Munich', country: 'Germany' },
  { code: 'DE-CO', name: 'Cologne', country: 'Germany' },
  { code: 'DE-FR', name: 'Frankfurt', country: 'Germany' },
  { code: 'DE-ST', name: 'Stuttgart', country: 'Germany' },
  { code: 'DE-DU', name: 'Düsseldorf', country: 'Germany' },
  { code: 'DE-DO', name: 'Dortmund', country: 'Germany' },
  { code: 'DE-ES', name: 'Essen', country: 'Germany' },
  { code: 'DE-LE', name: 'Leipzig', country: 'Germany' },
  
  // Italy
  { code: 'IT-RO', name: 'Rome', country: 'Italy' },
  { code: 'IT-MI', name: 'Milan', country: 'Italy' },
  { code: 'IT-NA', name: 'Naples', country: 'Italy' },
  { code: 'IT-TU', name: 'Turin', country: 'Italy' },
  { code: 'IT-PA', name: 'Palermo', country: 'Italy' },
  { code: 'IT-GE', name: 'Genoa', country: 'Italy' },
  { code: 'IT-BO', name: 'Bologna', country: 'Italy' },
  { code: 'IT-FL', name: 'Florence', country: 'Italy' },
  { code: 'IT-BA', name: 'Bari', country: 'Italy' },
  { code: 'IT-CA', name: 'Catania', country: 'Italy' },
  { code: 'IT-VE', name: 'Venice', country: 'Italy' },
  { code: 'IT-VR', name: 'Verona', country: 'Italy' },
  
  // Spain
  { code: 'ES-MA', name: 'Madrid', country: 'Spain' },
  { code: 'ES-BA', name: 'Barcelona', country: 'Spain' },
  { code: 'ES-VA', name: 'Valencia', country: 'Spain' },
  { code: 'ES-SE', name: 'Seville', country: 'Spain' },
  { code: 'ES-ZA', name: 'Zaragoza', country: 'Spain' },
  { code: 'ES-MA', name: 'Málaga', country: 'Spain' },
  { code: 'ES-MU', name: 'Murcia', country: 'Spain' },
  { code: 'ES-PA', name: 'Palma', country: 'Spain' },
  { code: 'ES-LA', name: 'Las Palmas', country: 'Spain' },
  { code: 'ES-BI', name: 'Bilbao', country: 'Spain' },
  
  // Turkey
  { code: 'TR-IS', name: 'Istanbul', country: 'Turkey' },
  { code: 'TR-AN', name: 'Ankara', country: 'Turkey' },
  { code: 'TR-IZ', name: 'Izmir', country: 'Turkey' },
  { code: 'TR-BU', name: 'Bursa', country: 'Turkey' },
  { code: 'TR-AD', name: 'Adana', country: 'Turkey' },
  { code: 'TR-GA', name: 'Gaziantep', country: 'Turkey' },
  { code: 'TR-KO', name: 'Konya', country: 'Turkey' },
  { code: 'TR-AN', name: 'Antalya', country: 'Turkey' },
  
  // Singapore
  { code: 'SG-SG', name: 'Singapore', country: 'Singapore' },
  
  // Malaysia
  { code: 'MY-KL', name: 'Kuala Lumpur', country: 'Malaysia' },
  { code: 'MY-JB', name: 'Johor Bahru', country: 'Malaysia' },
  { code: 'MY-IP', name: 'Ipoh', country: 'Malaysia' },
  { code: 'MY-KU', name: 'Kuching', country: 'Malaysia' },
  { code: 'MY-PE', name: 'Petaling Jaya', country: 'Malaysia' },
  { code: 'MY-SH', name: 'Shah Alam', country: 'Malaysia' },
  { code: 'MY-KO', name: 'Kota Kinabalu', country: 'Malaysia' },
  { code: 'MY-SE', name: 'Seremban', country: 'Malaysia' },
  
  // Thailand
  { code: 'TH-BK', name: 'Bangkok', country: 'Thailand' },
  { code: 'TH-CM', name: 'Chiang Mai', country: 'Thailand' },
  { code: 'TH-PH', name: 'Phuket', country: 'Thailand' },
  { code: 'TH-PA', name: 'Pattaya', country: 'Thailand' },
  { code: 'TH-HA', name: 'Hat Yai', country: 'Thailand' },
  { code: 'TH-KH', name: 'Khon Kaen', country: 'Thailand' },
  { code: 'TH-UD', name: 'Udon Thani', country: 'Thailand' },
  { code: 'TH-NA', name: 'Nakhon Ratchasima', country: 'Thailand' },
  
  // Indonesia
  { code: 'ID-JA', name: 'Jakarta', country: 'Indonesia' },
  { code: 'ID-SU', name: 'Surabaya', country: 'Indonesia' },
  { code: 'ID-ME', name: 'Medan', country: 'Indonesia' },
  { code: 'ID-BA', name: 'Bandung', country: 'Indonesia' },
  { code: 'ID-BE', name: 'Bekasi', country: 'Indonesia' },
  { code: 'ID-TA', name: 'Tangerang', country: 'Indonesia' },
  { code: 'ID-DE', name: 'Depok', country: 'Indonesia' },
  { code: 'ID-SE', name: 'Semarang', country: 'Indonesia' },
  { code: 'ID-PA', name: 'Palembang', country: 'Indonesia' },
  { code: 'ID-MA', name: 'Makassar', country: 'Indonesia' },
  
  // Philippines
  { code: 'PH-MA', name: 'Manila', country: 'Philippines' },
  { code: 'PH-QU', name: 'Quezon City', country: 'Philippines' },
  { code: 'PH-CE', name: 'Cebu City', country: 'Philippines' },
  { code: 'PH-DA', name: 'Davao City', country: 'Philippines' },
  { code: 'PH-CA', name: 'Caloocan', country: 'Philippines' },
  { code: 'PH-ZA', name: 'Zamboanga City', country: 'Philippines' },
  { code: 'PH-TA', name: 'Taguig', country: 'Philippines' },
  { code: 'PH-AN', name: 'Antipolo', country: 'Philippines' },
  
  // India
  { code: 'IN-MU', name: 'Mumbai', country: 'India' },
  { code: 'IN-DE', name: 'Delhi', country: 'India' },
  { code: 'IN-BA', name: 'Bangalore', country: 'India' },
  { code: 'IN-HY', name: 'Hyderabad', country: 'India' },
  { code: 'IN-AH', name: 'Ahmedabad', country: 'India' },
  { code: 'IN-CH', name: 'Chennai', country: 'India' },
  { code: 'IN-KO', name: 'Kolkata', country: 'India' },
  { code: 'IN-SU', name: 'Surat', country: 'India' },
  { code: 'IN-PU', name: 'Pune', country: 'India' },
  { code: 'IN-JA', name: 'Jaipur', country: 'India' },
  { code: 'IN-LU', name: 'Lucknow', country: 'India' },
  { code: 'IN-KA', name: 'Kanpur', country: 'India' },
  { code: 'IN-NA', name: 'Nagpur', country: 'India' },
  { code: 'IN-IN', name: 'Indore', country: 'India' },
  { code: 'IN-TH', name: 'Thane', country: 'India' },
  { code: 'IN-BH', name: 'Bhopal', country: 'India' },
  { code: 'IN-VI', name: 'Visakhapatnam', country: 'India' },
  { code: 'IN-PA', name: 'Patna', country: 'India' },
  { code: 'IN-VA', name: 'Vadodara', country: 'India' },
  { code: 'IN-GA', name: 'Ghaziabad', country: 'India' },
  
  // Pakistan
  { code: 'PK-KA', name: 'Karachi', country: 'Pakistan' },
  { code: 'PK-LA', name: 'Lahore', country: 'Pakistan' },
  { code: 'PK-FA', name: 'Faisalabad', country: 'Pakistan' },
  { code: 'PK-RA', name: 'Rawalpindi', country: 'Pakistan' },
  { code: 'PK-GU', name: 'Gujranwala', country: 'Pakistan' },
  { code: 'PK-PE', name: 'Peshawar', country: 'Pakistan' },
  { code: 'PK-MU', name: 'Multan', country: 'Pakistan' },
  { code: 'PK-HY', name: 'Hyderabad', country: 'Pakistan' },
  { code: 'PK-IS', name: 'Islamabad', country: 'Pakistan' },
  { code: 'PK-QU', name: 'Quetta', country: 'Pakistan' },
  
  // Bangladesh
  { code: 'BD-DH', name: 'Dhaka', country: 'Bangladesh' },
  { code: 'BD-CH', name: 'Chittagong', country: 'Bangladesh' },
  { code: 'BD-KH', name: 'Khulna', country: 'Bangladesh' },
  { code: 'BD-RA', name: 'Rajshahi', country: 'Bangladesh' },
  { code: 'BD-SY', name: 'Sylhet', country: 'Bangladesh' },
  { code: 'BD-BA', name: 'Barisal', country: 'Bangladesh' },
  { code: 'BD-RA', name: 'Rangpur', country: 'Bangladesh' },
  { code: 'BD-CO', name: 'Comilla', country: 'Bangladesh' },
  
  // China
  { code: 'CN-BE', name: 'Beijing', country: 'China' },
  { code: 'CN-SH', name: 'Shanghai', country: 'China' },
  { code: 'CN-GU', name: 'Guangzhou', country: 'China' },
  { code: 'CN-SZ', name: 'Shenzhen', country: 'China' },
  { code: 'CN-TI', name: 'Tianjin', country: 'China' },
  { code: 'CN-WU', name: 'Wuhan', country: 'China' },
  { code: 'CN-XI', name: 'Xi\'an', country: 'China' },
  { code: 'CN-CH', name: 'Chongqing', country: 'China' },
  { code: 'CN-HA', name: 'Hangzhou', country: 'China' },
  { code: 'CN-NA', name: 'Nanjing', country: 'China' },
  { code: 'CN-CH', name: 'Chengdu', country: 'China' },
  { code: 'CN-SH', name: 'Shenyang', country: 'China' },
  
  // Japan
  { code: 'JP-TO', name: 'Tokyo', country: 'Japan' },
  { code: 'JP-YO', name: 'Yokohama', country: 'Japan' },
  { code: 'JP-OS', name: 'Osaka', country: 'Japan' },
  { code: 'JP-NA', name: 'Nagoya', country: 'Japan' },
  { code: 'JP-SA', name: 'Sapporo', country: 'Japan' },
  { code: 'JP-FU', name: 'Fukuoka', country: 'Japan' },
  { code: 'JP-KO', name: 'Kobe', country: 'Japan' },
  { code: 'JP-KY', name: 'Kyoto', country: 'Japan' },
  { code: 'JP-KA', name: 'Kawasaki', country: 'Japan' },
  { code: 'JP-SA', name: 'Saitama', country: 'Japan' },
  
  // South Korea
  { code: 'KR-SE', name: 'Seoul', country: 'South Korea' },
  { code: 'KR-BU', name: 'Busan', country: 'South Korea' },
  { code: 'KR-IN', name: 'Incheon', country: 'South Korea' },
  { code: 'KR-DA', name: 'Daegu', country: 'South Korea' },
  { code: 'KR-DA', name: 'Daejeon', country: 'South Korea' },
  { code: 'KR-GW', name: 'Gwangju', country: 'South Korea' },
  { code: 'KR-SU', name: 'Suwon', country: 'South Korea' },
  { code: 'KR-UL', name: 'Ulsan', country: 'South Korea' },
  
  // Australia
  { code: 'AU-SY', name: 'Sydney', country: 'Australia' },
  { code: 'AU-ME', name: 'Melbourne', country: 'Australia' },
  { code: 'AU-BR', name: 'Brisbane', country: 'Australia' },
  { code: 'AU-PE', name: 'Perth', country: 'Australia' },
  { code: 'AU-AD', name: 'Adelaide', country: 'Australia' },
  { code: 'AU-GO', name: 'Gold Coast', country: 'Australia' },
  { code: 'AU-CA', name: 'Canberra', country: 'Australia' },
  { code: 'AU-NEW', name: 'Newcastle', country: 'Australia' },
  { code: 'AU-WO', name: 'Wollongong', country: 'Australia' },
  { code: 'AU-DA', name: 'Darwin', country: 'Australia' },
  
  // New Zealand
  { code: 'NZ-AU', name: 'Auckland', country: 'New Zealand' },
  { code: 'NZ-WE', name: 'Wellington', country: 'New Zealand' },
  { code: 'NZ-CH', name: 'Christchurch', country: 'New Zealand' },
  { code: 'NZ-HA', name: 'Hamilton', country: 'New Zealand' },
  { code: 'NZ-TA', name: 'Tauranga', country: 'New Zealand' },
  { code: 'NZ-DU', name: 'Dunedin', country: 'New Zealand' },
  
  // Brazil
  { code: 'BR-SP', name: 'São Paulo', country: 'Brazil' },
  { code: 'BR-RJ', name: 'Rio de Janeiro', country: 'Brazil' },
  { code: 'BR-BR', name: 'Brasília', country: 'Brazil' },
  { code: 'BR-SA', name: 'Salvador', country: 'Brazil' },
  { code: 'BR-FO', name: 'Fortaleza', country: 'Brazil' },
  { code: 'BR-BH', name: 'Belo Horizonte', country: 'Brazil' },
  { code: 'BR-MA', name: 'Manaus', country: 'Brazil' },
  { code: 'BR-CU', name: 'Curitiba', country: 'Brazil' },
  { code: 'BR-RE', name: 'Recife', country: 'Brazil' },
  { code: 'BR-PO', name: 'Porto Alegre', country: 'Brazil' },
  { code: 'BR-BE', name: 'Belém', country: 'Brazil' },
  { code: 'BR-GO', name: 'Goiânia', country: 'Brazil' },
  
  // Argentina
  { code: 'AR-BA', name: 'Buenos Aires', country: 'Argentina' },
  { code: 'AR-CO', name: 'Córdoba', country: 'Argentina' },
  { code: 'AR-RO', name: 'Rosario', country: 'Argentina' },
  { code: 'AR-ME', name: 'Mendoza', country: 'Argentina' },
  { code: 'AR-TU', name: 'Tucumán', country: 'Argentina' },
  { code: 'AR-LP', name: 'La Plata', country: 'Argentina' },
  { code: 'AR-MD', name: 'Mar del Plata', country: 'Argentina' },
  { code: 'AR-SA', name: 'Salta', country: 'Argentina' },
  
  // Mexico
  { code: 'MX-MC', name: 'Mexico City', country: 'Mexico' },
  { code: 'MX-GU', name: 'Guadalajara', country: 'Mexico' },
  { code: 'MX-MO', name: 'Monterrey', country: 'Mexico' },
  { code: 'MX-PU', name: 'Puebla', country: 'Mexico' },
  { code: 'MX-TI', name: 'Tijuana', country: 'Mexico' },
  { code: 'MX-LE', name: 'León', country: 'Mexico' },
  { code: 'MX-JU', name: 'Juárez', country: 'Mexico' },
  { code: 'MX-TO', name: 'Torreón', country: 'Mexico' },
  { code: 'MX-QU', name: 'Querétaro', country: 'Mexico' },
  { code: 'MX-CH', name: 'Chihuahua', country: 'Mexico' },
  
  // South Africa
  { code: 'ZA-JO', name: 'Johannesburg', country: 'South Africa' },
  { code: 'ZA-CT', name: 'Cape Town', country: 'South Africa' },
  { code: 'ZA-DU', name: 'Durban', country: 'South Africa' },
  { code: 'ZA-PR', name: 'Pretoria', country: 'South Africa' },
  { code: 'ZA-PE', name: 'Port Elizabeth', country: 'South Africa' },
  { code: 'ZA-PI', name: 'Pietermaritzburg', country: 'South Africa' },
  { code: 'ZA-BE', name: 'Benoni', country: 'South Africa' },
  { code: 'ZA-TE', name: 'Tembisa', country: 'South Africa' },
  
  // Nigeria
  { code: 'NG-LA', name: 'Lagos', country: 'Nigeria' },
  { code: 'NG-KA', name: 'Kano', country: 'Nigeria' },
  { code: 'NG-IB', name: 'Ibadan', country: 'Nigeria' },
  { code: 'NG-AB', name: 'Abuja', country: 'Nigeria' },
  { code: 'NG-PH', name: 'Port Harcourt', country: 'Nigeria' },
  { code: 'NG-BE', name: 'Benin City', country: 'Nigeria' },
  { code: 'NG-MA', name: 'Maiduguri', country: 'Nigeria' },
  { code: 'NG-ZA', name: 'Zaria', country: 'Nigeria' },
  
  // Kenya
  { code: 'KE-NA', name: 'Nairobi', country: 'Kenya' },
  { code: 'KE-MO', name: 'Mombasa', country: 'Kenya' },
  { code: 'KE-KI', name: 'Kisumu', country: 'Kenya' },
  { code: 'KE-NA', name: 'Nakuru', country: 'Kenya' },
  { code: 'KE-EL', name: 'Eldoret', country: 'Kenya' },
  { code: 'KE-ME', name: 'Meru', country: 'Kenya' },
  
  // Russia
  { code: 'RU-MO', name: 'Moscow', country: 'Russia' },
  { code: 'RU-SP', name: 'Saint Petersburg', country: 'Russia' },
  { code: 'RU-NO', name: 'Novosibirsk', country: 'Russia' },
  { code: 'RU-EK', name: 'Yekaterinburg', country: 'Russia' },
  { code: 'RU-NN', name: 'Nizhny Novgorod', country: 'Russia' },
  { code: 'RU-KA', name: 'Kazan', country: 'Russia' },
  { code: 'RU-CH', name: 'Chelyabinsk', country: 'Russia' },
  { code: 'RU-OM', name: 'Omsk', country: 'Russia' },
  { code: 'RU-SA', name: 'Samara', country: 'Russia' },
  { code: 'RU-RO', name: 'Rostov-on-Don', country: 'Russia' }
]