project_id = "klwolsopucgswhtdlsps"

[functions.tryon-start]
verify_jwt = true

[functions.tryon-status]
verify_jwt = true

[functions.bitstudio-tryon]
verify_jwt = true

[functions.user-setup-hook]
verify_jwt = false