
import "https://deno.land/x/xhr@0.1.0/mod.ts";
import { serve } from "https://deno.land/std@0.168.0/http/server.ts";

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

const openAIApiKey = Deno.env.get('OPENAI_API_KEY');

const LEGO_PROMPT = `Create a LEGO mini-figure version of the person in the uploaded photo, wearing the exact same outfit, accessories, and hairstyle. Replicate all clothing details, patterns, and colors exactly, including any printed text on clothing, denim styles, jewelry, headwear, phone case designs, handbags, or boots. The LEGO figure should mimic the identical facial expression, stance, and pose as the person in the image, while holding the same objects in the same way. Maintain realistic LEGO proportions and brick-like textures while ensuring accurate color matching to the original photo. Render with a transparent background and no shadows so it can be used in various layouts. The style should be consistent with authentic LEGO mini-figure aesthetics.`;

async function fetchAsDataUrl(url: string): Promise<string> {
  console.log('Fetching image from:', url);
  const response = await fetch(url);
  if (!response.ok) {
    throw new Error(`Failed to fetch image: ${response.status} ${response.statusText}`);
  }
  
  const contentType = response.headers.get("content-type") || "image/jpeg";
  const arrayBuffer = await response.arrayBuffer();
  const base64 = btoa(String.fromCharCode(...new Uint8Array(arrayBuffer)));
  return `data:${contentType};base64,${base64}`;
}

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  const url = new URL(req.url);
  
  // Health endpoint
  if (req.method === 'GET' && url.pathname.endsWith('/health')) {
    const hasKey = !!openAIApiKey;
    return new Response(JSON.stringify({
      ok: hasKey,
      model: "gpt-4.1-mini + image_generation",
      hasKey: hasKey,
      apiType: "Responses API with image_generation tool"
    }), {
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      status: hasKey ? 200 : 500,
    });
  }

  if (req.method !== 'POST') {
    return new Response(JSON.stringify({ error: "Method Not Allowed" }), {
      status: 405,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });
  }

  try {
    if (!openAIApiKey) {
      return new Response(JSON.stringify({ error: "OPENAI_API_KEY missing in function environment" }), {
        status: 401,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }

    const requestBody = await req.json().catch(() => ({}));
    const { sourceUrl } = requestBody;

    if (!sourceUrl) {
      return new Response(JSON.stringify({ error: "sourceUrl is required" }), {
        status: 400,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }

    console.log('Processing toy replica generation for sourceUrl:', sourceUrl);

    // Get the uploaded image as a data URL
    const dataUrl = await fetchAsDataUrl(sourceUrl);
    console.log('Image fetched and converted to data URL');

    // Call OpenAI Responses API with image_generation tool
    console.log('Calling OpenAI Responses API...');
    const response = await fetch('https://api.openai.com/v1/responses', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${openAIApiKey}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        model: 'gpt-4.1-mini',
        input: [
          {
            role: 'user',
            content: [
              { type: 'input_text', text: LEGO_PROMPT },
              { type: 'input_image', image_url: dataUrl }
            ]
          }
        ],
        tools: [{ type: 'image_generation' }]
      }),
    });

    console.log('OpenAI API response status:', response.status);

    if (!response.ok) {
      const errorText = await response.text();
      console.error('OpenAI API error:', errorText);
      return new Response(JSON.stringify({ 
        error: `OpenAI API failed: ${response.status} ${errorText}` 
      }), {
        status: 502,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }

    const result = await response.json();
    console.log('OpenAI API response received');

    // Extract the generated image
    const imageGenerationCall = result.output?.find((o: any) => o.type === 'image_generation_call');
    const base64Image = imageGenerationCall?.result;

    if (!base64Image) {
      console.error('No image returned from OpenAI:', result);
      return new Response(JSON.stringify({ 
        error: "No image was generated by OpenAI",
        raw: result 
      }), {
        status: 502,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }

    console.log('LEGO mini-figure generation completed successfully');

    return new Response(JSON.stringify({ 
      b64_png: base64Image 
    }), {
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      status: 200,
    });

  } catch (error) {
    console.error('Error in generate-toy-replica function:', error);
    
    // Always return the precise error so the frontend can show it
    return new Response(JSON.stringify({ 
      error: error instanceof Error ? error.message : String(error)
    }), {
      status: 500,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });
  }
});
