// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.22.2";

// src/lib/mcp/tools/list-wardrobe-items.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z } from "npm:zod@^3.23.8";

// src/lib/mcp/tools/supabase-client.ts
import { createClient } from "npm:@supabase/supabase-js@^2.78.0";
function supabaseForUser(ctx) {
  const url = process.env.SUPABASE_URL;
  const key = process.env.SUPABASE_PUBLISHABLE_KEY;
  if (!url || !key) {
    throw new Error("Supabase environment variables are not configured");
  }
  return createClient(url, key, {
    global: {
      headers: {
        Authorization: `Bearer ${ctx.getToken()}`
      }
    },
    auth: {
      persistSession: false,
      autoRefreshToken: false
    }
  });
}

// src/lib/mcp/tools/list-wardrobe-items.ts
var list_wardrobe_items_default = defineTool({
  name: "list_wardrobe_items",
  title: "List wardrobe items",
  description: "List the signed-in user's wardrobe clothing items.",
  inputSchema: {
    limit: z.number().int().min(1).max(50).default(20).describe("Maximum items to return")
  },
  annotations: {
    readOnlyHint: true,
    idempotentHint: true,
    openWorldHint: false
  },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser(ctx).from("wardrobe_items").select("id, name, category, brand, color, image_url, image_bg_removed_url, tags, created_at").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: `Found ${data?.length ?? 0} wardrobe item(s).` }],
      structuredContent: { items: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/add-wardrobe-item.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z2 } from "npm:zod@^3.23.8";
var add_wardrobe_item_default = defineTool2({
  name: "add_wardrobe_item",
  title: "Add wardrobe item",
  description: "Add a clothing item to the signed-in user's wardrobe by image URL and category.",
  inputSchema: {
    image_url: z2.string().url().describe("Public URL of the clothing item image"),
    category: z2.string().min(1).describe("Clothing category, e.g. tops, bottoms, dresses, shoes"),
    name: z2.string().optional().describe("Optional display name for the item"),
    brand: z2.string().optional().describe("Optional brand name"),
    color: z2.string().optional().describe("Optional color")
  },
  annotations: {
    readOnlyHint: false,
    idempotentHint: false,
    openWorldHint: false
  },
  handler: async ({ image_url, category, name, brand, color }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser(ctx).from("wardrobe_items").insert({
      user_id: ctx.getUserId(),
      image_url,
      category,
      name: name ?? null,
      brand: brand ?? null,
      color: color ?? null
    }).select("id, name, category, brand, color, image_url, created_at").single();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: "Wardrobe item added." }],
      structuredContent: { item: data }
    };
  }
});

// src/lib/mcp/tools/list-liked-products.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z3 } from "npm:zod@^3.23.8";
var list_liked_products_default = defineTool3({
  name: "list_liked_products",
  title: "List liked products",
  description: "List products the signed-in user has liked.",
  inputSchema: {
    limit: z3.number().int().min(1).max(50).default(20).describe("Maximum products to return")
  },
  annotations: {
    readOnlyHint: true,
    idempotentHint: true,
    openWorldHint: false
  },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser(ctx).from("likes").select("id, product_id, created_at, products(id, title, brand_id, price_cents, currency, image_url, external_url)").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: `Found ${data?.length ?? 0} liked product(s).` }],
      structuredContent: { likes: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-wishlist-items.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z4 } from "npm:zod@^3.23.8";
var list_wishlist_items_default = defineTool4({
  name: "list_wishlist_items",
  title: "List wishlist items",
  description: "List products the signed-in user has added to their wishlist.",
  inputSchema: {
    limit: z4.number().int().min(1).max(50).default(20).describe("Maximum items to return")
  },
  annotations: {
    readOnlyHint: true,
    idempotentHint: true,
    openWorldHint: false
  },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const userId = ctx.getUserId();
    const { data: wishlist, error: wishlistError } = await supabase.from("wishlists").select("id").eq("user_id", userId).single();
    if (wishlistError) {
      return { content: [{ type: "text", text: wishlistError.message }], isError: true };
    }
    const { data, error } = await supabase.from("wishlist_items").select("id, added_at, products(id, title, brand_id, price_cents, currency, image_url, external_url)").eq("wishlist_id", wishlist.id).order("added_at", { ascending: false }).limit(limit);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: `Found ${data?.length ?? 0} wishlist item(s).` }],
      structuredContent: { items: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-user-outfits.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z5 } from "npm:zod@^3.23.8";
var list_user_outfits_default = defineTool5({
  name: "list_user_outfits",
  title: "List user outfits",
  description: "List outfits created by the signed-in user.",
  inputSchema: {
    limit: z5.number().int().min(1).max(50).default(20).describe("Maximum outfits to return")
  },
  annotations: {
    readOnlyHint: true,
    idempotentHint: true,
    openWorldHint: false
  },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser(ctx).from("fits").select("id, name, title, occasion, context, image_preview, is_public, created_at").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: `Found ${data?.length ?? 0} outfit(s).` }],
      structuredContent: { outfits: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-user-profile.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.22.2";
var get_user_profile_default = defineTool6({
  name: "get_user_profile",
  title: "Get user profile",
  description: "Return the signed-in user's public profile metadata.",
  inputSchema: {},
  annotations: {
    readOnlyHint: true,
    idempotentHint: true,
    openWorldHint: false
  },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const userId = ctx.getUserId();
    const { data, error } = await supabaseForUser(ctx).from("public_profiles").select("id, name, username, avatar_url, bio, country, role, is_public, website").eq("id", userId).single();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: "User profile loaded." }],
      structuredContent: { profile: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "klwolsopucgswhtdlsps";
var mcp_default = defineMcp({
  name: "azyah-style-mcp",
  title: "Azyah Style MCP",
  version: "0.1.0",
  instructions: "Azyah Style personal fashion assistant. Tools let a signed-in user inspect and manage their wardrobe items, liked products, wishlist, outfits, and public profile. All tools operate as the authenticated user via Supabase RLS.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_wardrobe_items_default,
    add_wardrobe_item_default,
    list_liked_products_default,
    list_wishlist_items_default,
    list_user_outfits_default,
    get_user_profile_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
