// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { getSupabaseUrl } from '@/utils/storageUrlHelper';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://klwolsopucgswhtdlsps.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtsd29sc29wdWNnc3dodGRsc3BzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyNTQ4NTIsImV4cCI6MjA2OTgzMDg1Mn0.t1GFgR9xiIh7PBmoYs_xKLi1fF1iLTF6pqMlLMHowHQ";

// Dev-only console log to verify environment variables
if (import.meta.env.DEV) {
  console.log('SUPABASE_URL:', SUPABASE_URL);
  console.log('Using hybrid approach: Custom proxy for API, direct Supabase for storage');
}

// Main Supabase client (uses custom proxy for API calls)
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  global: {
    headers: { apikey: SUPABASE_PUBLISHABLE_KEY }
  }
});

// Direct Supabase client for storage operations (bypasses proxy)
export const supabaseStorage = createClient<Database>(
  "https://klwolsopucgswhtdlsps.supabase.co", 
  SUPABASE_PUBLISHABLE_KEY, 
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    },
    global: {
      headers: { apikey: SUPABASE_PUBLISHABLE_KEY }
    }
  }
);